runtime: go
api_version: go1

handlers:
  - url: /(.*\.(css|js|jpg|png))$
    static_files: client/dest/\1
    upload: client/dest/.*\.(css|js|jpg|png)$
  - url: /
    static_files: client/index.html
    upload: client/index.html
  - url: /.*
    script: _go_app